### ISSUE TITLE
Adding language metadata when uploading files to XTRF

### ISSUE THREAD

**Issue by ben-miller-MCC** [bb-io/XTRF#1]
Adding language meta data when uploading files is not quite functional yet and is a bit complicated, in part because which fields can be used depends on the file category… The API really is hard to work with in this regard, unfortunately, and all of the information below is undocumented, AFAIK, and entirely based on my experience and troubleshooting 😉

I see 3 main issues here:
1. Which fields apply to the file depends on its category. Most categories accept only the `languages` field, but bilingual file formats accept only the `languageCombinations` field – this applies to `Bilingual Document`, `CAT Analysis`, `Terminology`, `Translation Memory`. As far as I can tell, neither field is ever **required**, so both should be **optional** inputs.
2. The `languages` field takes an array of language IDs, so even if I want to specify 1 language, I need to pass an array. This is impossible when iterating over languages in a loop:
<img width="400" alt="adding language ID in a loop" src="https://github.com/bb-io/XTRF/assets/71875509/9c5f8352-0a2d-4e5a-a251-99d1973c848e">

3. Similarly, the `languageCombinations` field (which is currently not implemented as an input yet) takes a list of dicts, so when adding a source and target language, I would once again not be able to do it in a loop, which is of course where I need to do it.

I have a suggestion, which I believe will cover all issues above. In practice, I have very rarely needed the ability to assign multiple languages or language combinations to a file on upload. If no language information is passed, the file lists `Any` as the language in XTRF, which is perfectly acceptable for reference files and similar files. Source files and translated files should usually be assigned 1 language, and bilingual files must also only have 1 language combination.

So I suggest creating two **optional** inputs:
- `Language`, which accepts a single language ID (as text, for consistency)
- `Language combination`, which accepts a single source and single target language ID (as text). (I'm not sure what this would look like in Blackbird, but in my head selecting the optional input `Language combination` causes 2 inputs to show up, `Source language` and `Target language`.)

In this case, the user has to know which option to use with the selected category. Of course, Blackbird could also make the available optional inputs depend on the selected category, if that's easy to implement.

Either way, this would rule out being able to assign multiple languages (or combinations) to a file, but I really have no ideas on how to make that possible while also making it possible to pass a single language ID while in a loop…

**Comment by ben-miller-MCC** [comment]
Here are some additional resources I found:
- [XTRF file categories](https://xtrf.userecho.com/knowledge-bases/6/articles/234-file-categories) (not much information on language assignment though)
- [Files auto-categorization & language detection in XTRF​](https://xtrf.userecho.com/knowledge-bases/6/articles/235-files-auto-categorization-language-detection)

**Comment by bZverok** [comment]
@ben-miller-MCC Language combination is already implemented as an optional input: 
![image](https://github.com/bb-io/XTRF/assets/137277669/2ffa559c-873f-4651-a518-1257be820e06)

**Comment by bZverok** [comment]
We currently cannot make input schema dynamic depending on your Category input, so all of these values should be optional, you are right

**Comment by bZverok** [comment]
https://github.com/bb-io/XTRF/commit/d73faf1c91d25074084a72fb97382f8fe6df1a90

**Comment by ben-miller-MCC** [comment]
Hi @bZverok, thank you, it looks good, but currently I can't test the upload of bilingual documents because of #2. However, uploading a file with only 1 language (using the optional `Language` field) works perfectly 👍🏻
